name: lock_box
description: "A password manager app for Hollander Landscaping. Users within the organization can view and manage passwords for various accounts and allow them to be shared temporarily."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.14.0
  firebase_ui_oauth_google: ^1.2.17
  firebase_ui_auth: ^1.12.1
  google_fonts: ^6.1.0
  provider: ^6.1.1
  url_launcher: ^6.2.3
  envied: ^0.5.3
  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.3.1
  flutter_native_splash: ^2.3.9


flutter_launcher_icons:
  image_path: "assets/logo.png"
  web:
    generate: true
    background_color: #f7ffee
    theme_color: #8bb93f

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  envied_generator: ^0.5.3
  build_runner: ^2.4.8

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/logo.png
