// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpkOWN8DojHp2gMrH-7l6PUMJc2KSNV18',
    appId: '1:544751736057:web:faf1d0d216ad82e95d3e28',
    messagingSenderId: '544751736057',
    projectId: 'lockbox-hollander',
    authDomain: 'lockbox-hollander.firebaseapp.com',
    storageBucket: 'lockbox-hollander.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu9b6r3mnMjeOgpKJ4E8gIIHcEITg27o0',
    appId: '1:544751736057:android:e77361b01d5931125d3e28',
    messagingSenderId: '544751736057',
    projectId: 'lockbox-hollander',
    storageBucket: 'lockbox-hollander.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoU4lEtZs-f_ccfhNZYNxMFO6Q86bKAvk',
    appId: '1:544751736057:ios:d67084699d3f07ad5d3e28',
    messagingSenderId: '544751736057',
    projectId: 'lockbox-hollander',
    storageBucket: 'lockbox-hollander.appspot.com',
    iosClientId: '544751736057-fen62b4nb8kf9kr8igrahs808l8ven8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.lockBox',
  );
}
